version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"

  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    depends_on:
      - mysql
